# Generated by Django 2.1.6 on 2019-05-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productinorder_nmb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
